[VSP] save last used VSP host
decred/decrediton pull request #2789
Opened 2020-10-26 06:22 UTC by bgptr

This update saves the last used VSP host to config after a successful ticket purchase on the new VSP page and sets the VSPSelects when the user arrives next time.
Closes #2763

2020-10-26 11:51 UTC, vctt94 commented on app/actions/ControlActions.js
> +    const config = getGlobalCfg();
This shouldn't be a global config, but a wallet config instead

2020-10-26 11:54 UTC, vctt94 requested changes
Thanks for this PR.

The vsp should be a wallet config and not a global config, as each wallet can have different vsps selected, as default.

2020-10-26 14:31 UTC, bgptr commented
Thank you for thre review. 
I moved the vsp_host param to the wallet config.

2020-10-26 15:28 UTC, degeri commented
can we have this as an optional clickable setting ? worried about centralization risks here. We want people to feel like they can choose any VSP they want.

2020-10-26 15:51 UTC, vctt94 commented
I think that's a valid point @degeri. Maybe we can have a checkbox near the ticket purchase area saying `use default`. What do you think @bgptr ?

2020-10-26 17:37 UTC, bgptr commented
@vctt94 @degeri Sure thing, I have added the checkbox.

2020-10-27 11:49 UTC, jholdstock commented
I've tried out the checkbox, I like the idea but it needs refining. I suggest

- Checkbox label should read "Always use this VSP"
- If no VSP is selected (ie. the dropdown says "Select VSP...") the checkbox should be hidden/deactivated. When a VSP is selected, checkbox appears/activates.
- When the checkbox is checked, the dropdown is deactivated to indicate that the value can not be changed. Checkbox must be unchecked again before dropdown value can change.

2020-10-27 13:26 UTC, bgptr commented
@jholdstock I like your suggestions. I've implemented them.

2020-10-27 15:13 UTC, jholdstock commented
Looking better but it seems like the selected vsp and checkbox are resetting when I closed/reopen decrediton.

Edit: Actually, I dont even need to restart decrediton. Just opening a new tab resets the values.

2020-10-27 19:27 UTC, bgptr commented
@jholdstock You are right. Probably it's because I saved the VSP host only after successful ticket purchasing. 

I revamped (and also cleaned up) the code to save immediately after clicking on the checkbox. 
It's more user-friendly now. Thank you.

2020-10-27 21:43 UTC, vctt94 commented
needs rebase

2020-10-27 21:58 UTC, bgptr commented
rebased

2020-10-28 15:22 UTC, vctt94 approved these changes
I think that's a good start and we can start from here. Thanks @bgptr

2020-10-28 15:30 UTC, merged