[startup] Filter incomplete setup wallets in wallet selection
decred/decrediton pull request #2937
Opened 2020-11-14 21:21 UTC by amassarwi

This diff fixes #2920 by filtering out incomplete setup wallet in available wallets list.

2020-11-16 15:21 UTC, vctt94 requested changes
I don't think the wallet which are incompleted should be filtered. It should allow to complete its setup, if wanted.

2020-11-16 15:57 UTC, amassarwi commented
@vctt94 Right, i need to cleanup incomplete wallet on shutdown tho, as we do don't have access to the seed after a shutdown and we can't validate it if user restarted decrediton and tried to restore his wallet.

Sounds doable to you ?

2020-11-18 16:48 UTC, vctt94 commented
Incomplete setup shows when the directories for the wallet are created, but it doesn't have a wallet.db file. 

So for finishing the setup it needs to create a new wallet, which will generate a new seed.

2020-11-20 20:34 UTC, amassarwi commented
I see, will do

2022-02-01 22:51 UTC, alexlyp commented
Going to complete this in an alternative PR.  I think we need to let people complete the set up instead of just not showing them the incomplete ones.

2022-02-01 22:51 UTC, closed without merging