[get-started] style: improve messaging on restore wallet form
decred/decrediton pull request #3032
Opened 2020-12-01 22:48 UTC by victorgcramos

This diff adds tooltips for Watch Only and Trezor, since Privacy will be removed by #3020, and adds an "Advanced Options" label.

Closes #3020 

<img width="1670" alt="Screen Shot 2020-12-01 at 6 52 14 PM" src="https://user-images.githubusercontent.com/22639213/100802536-6abbb000-3408-11eb-81b2-f860fd7d68f9.png">
<img width="1671" alt="Screen Shot 2020-12-01 at 6 52 04 PM" src="https://user-images.githubusercontent.com/22639213/100802557-70b19100-3408-11eb-8a84-fc0aa74f7834.png">

2020-12-03 14:05 UTC, jholdstock commented
I had thought that the "Advanced Options" would be a collapsible panel, which is hidden by default. Just adding a heading doesnt really add much value IMO.

Now that I am seeing it, I'm not sure if tooltip is correct for this. It isnt obvious that the toggle labels can be hovered over. 

Perhaps we could use a light italic text, under the toggle, similar to the LN and settings tabs:

![Screenshot from 2020-12-03 14-03-25](https://user-images.githubusercontent.com/6762864/101027794-690cfc00-3570-11eb-90b2-bbde4f7fdc28.png)
![Screenshot from 2020-12-03 14-03-36](https://user-images.githubusercontent.com/6762864/101027795-690cfc00-3570-11eb-9a76-9f339d9f6772.png)

2020-12-03 14:24 UTC, victorgcramos commented
Nice suggestion! I really like it!

2020-12-03 16:24 UTC, victorgcramos commented
<img width="1157" alt="Screen Shot 2020-12-03 at 1 18 35 PM" src="https://user-images.githubusercontent.com/22639213/101057495-dae24700-356a-11eb-89d7-630c00fda0e9.png">

@jholdstock what about now?

2020-12-04 14:50 UTC, vctt94 reviewed
I think that's a good improvement. Thanks for this PR.

About watching only wallet, it is true that you can not spend any decred, but you can not do any actions, which would need signing, as a watch only wallet does not know the wallet seed. 

So Also creating account, signing messages, etc. Not sure what would be a good message for that, but I'd like to make it clearer

2020-12-07 10:16 UTC, jholdstock commented
I think the current message for watch only is acceptable. We should not spam the user with information on this page. We can add a link to docs.decred.org once decred/dcrdocs#1137 is implemented

2020-12-07 10:37 UTC, jholdstock requested changes
We should keep the watch-only message reasonably short so we don't spam the user with information on this page. For more information, we can add a link to docs.decred.org once decred/dcrdocs#1137 is implemented.

How about this:

> A watch-only wallet has limited functionality. It can only be used to view the balance and monitor transaction history. You won't be able to spend any DCR associated with this wallet.

And for the Trezor message:

> Trezor is a hardware wallet. For more information, visit **docs.decred.org**

Linking to https://docs.decred.org/wallets/decrediton/trezor/


![Screenshot from 2020-12-07 10-33-14](https://user-images.githubusercontent.com/6762864/101340431-a5de3900-3877-11eb-9e8e-118abe3b8e52.png)

I'd suggest indenting the "Master pub key" field so it is aligned with the "You'll not be able..." message, or perhaps even indented slighted more than that.

And also, can we limit the width of the "Advanced Options" panel? It seems a bit too wide at the moment. max-width around 600px looks good to my eye.

2020-12-07 14:28 UTC, victorgcramos commented
Preview:

<img width="1291" alt="Screen Shot 2020-12-07 at 11 27 52 AM" src="https://user-images.githubusercontent.com/22639213/101362731-408e4600-387f-11eb-80c3-4dc1a1089820.png">

2020-12-07 15:06 UTC, jholdstock approved these changes
Great work :+1:

2021-01-05 16:56 UTC, merged