[privacy][wip] Auto-detect mixed wallet
decred/decrediton pull request #3033
Opened 2020-12-02 00:13 UTC by amassarwi

This diff deletes current `Privacy` toggle from wallet restore page and auto detects mixed wallet by 
checking for coinjoin outputs on startup.

---

Based on #3029 
Closes #2907

2020-12-02 22:59 UTC, amassarwi commented on app/components/views/GetStartedPage/hooks.js
> +            .then(() => {
not needed `{}`

2020-12-03 13:31 UTC, jholdstock commented
I've recovered a wallet with coinjoins, and set my mixed/unmixed accounts correctly. Opening the privacy tab i see some issues:

- My unmixed account has 0.99 dcr balance, however the large "Unmixed Balance" on the privacy tab is showing 0.00
- The smaller unmixed balance, in the Send to Unmixed account panel, is correctly shown as 0.99
- The "Start Mix" button is activated, even though my balance is 0. Would expect a low balance warning
- My mixed and unmixed account names are not shown at the top of the privacy tab, I have the generic message instead, which is shown when account names are not yet set.

I've tried to demonstrate the issues in the gif below

![Peek 2020-12-03 13-26](https://user-images.githubusercontent.com/6762864/101024146-9c00c100-356b-11eb-97b9-0fed94722df0.gif)

2020-12-03 13:37 UTC, amassarwi commented
@jholdstock Thanks for the review, It might be master issue as well - looking into it.

2020-12-03 22:39 UTC, amassarwi commented
@jholdstock hrmm i can't reproduce - i just restored privacy wallet and got the right unmixed balance everywhere.
I also see `mixed` & `unmixed` highlighted account names in the header.

Can you please double check if you are running latest commit of this PR?

2020-12-04 09:19 UTC, jholdstock commented
I've played around some more and this seems to occur if I set account index 0 as the unmixed account.

2020-12-04 15:58 UTC, amassarwi commented
hrmm interesting 🤔

2020-12-04 22:46 UTC, amassarwi commented
Fixed, 0 == undefined == false issue.

2020-12-07 09:33 UTC, jholdstock requested changes
Fixing the `0 == undefined == false` issue is good, but I think the proper fix here should be to remove the checkboxes from account 0 on the "Set Mixed Account" page. If using default as mixed/unmixed is not supported, it shouldnt be presented to the user as an option

![Screenshot from 2020-12-07 09-32-09](https://user-images.githubusercontent.com/6762864/101334019-3c5a2c80-386f-11eb-94e1-e7298ca2b709.png)

2020-12-07 17:16 UTC, amassarwi commented
@jholdstock updated

2020-12-08 13:22 UTC, jholdstock commented
I am trying to create a new wallet and getting stuck at this screen:

![Screenshot from 2020-12-08 13-19-19](https://user-images.githubusercontent.com/6762864/101489107-60456d00-3958-11eb-9f88-c00ff26db071.png)


A warning in the electron logs
```
utils.js:449 Warning: No implementation found for action type 'isAtSettingAccount'
warn	@	utils.js:449
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.exec	@	interpreter.js:762
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.execute	@	interpreter.js:223
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.update	@	interpreter.js:243
(anonymous)	@	interpreter.js:144
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.process	@	scheduler.js:59
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.schedule	@	scheduler.js:43
Interpreter.send	@	interpreter.js:140
isSyncingRPC	@	hooks.js:238
async function (async)		
isSyncingRPC	@	hooks.js:229
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.exec	@	interpreter.js:650
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.execute	@	interpreter.js:223
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.update	@	interpreter.js:243
(anonymous)	@	interpreter.js:144
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.process	@	scheduler.js:59
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.schedule	@	scheduler.js:43
Interpreter.send	@	interpreter.js:140
(anonymous)	@	hooks.js:183
Promise.then (async)		
isAtStartWallet	@	hooks.js:170
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.exec	@	interpreter.js:650
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.execute	@	interpreter.js:223
module.exports../node_modules/xstate/lib/interpreter.js.Interpreter.update	@	interpreter.js:243
(anonymous)	@	interpreter.js:144
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.process	@	scheduler.js:59
module.exports../node_modules/xstate/lib/scheduler.js.Scheduler.schedule	@	scheduler.js:43
Interpreter.send	@	interpreter.js:140
(anonymous)	@	hooks.js:350
onClick	@	Form.jsx:157
callCallback	@	react-dom.development.js:189
invokeGuardedCallbackDev	@	react-dom.development.js:238
Show 20 more frames
```

2020-12-09 16:44 UTC, jholdstock approved these changes
Works for me!

2021-01-04 20:14 UTC, vctt94 commented
Needs rebase

2021-01-05 00:52 UTC, amassarwi commented
@vctt94 rebased

2021-01-07 17:57 UTC, alexlyp approved these changes

2021-01-07 17:57 UTC, merged