Move allowed external requests to wallet config
decred/decrediton pull request #3045
Opened 2020-12-06 00:24 UTC by guilhermemntt

This PR moves ``allowed_external_requests`` to each wallet particular configuration. This change maintains the global flag, although it can only be used and set in GetStartedPage, when no wallet has been started yet. This PR also define wallet config flags in ``app/constants/config.js`` in the same way it's already implemented for global flags.

2020-12-06 09:59 UTC, amassarwi reviewed
Looks good overall, left few small nits

2020-12-06 09:59 UTC, amassarwi commented on app/actions/LNActions.js
> -        addrAccount
could use string template here

2020-12-06 09:59 UTC, amassarwi commented on app/constants/config.js
> +export const ENABLE_TICKET_BUYER = "enableticketbuyer";
👏

2020-12-06 09:59 UTC, amassarwi commented on app/constants/config.js
> +
extra empty line

2020-12-06 09:59 UTC, amassarwi commented on app/constants/config.js
> +
extra empty line

2020-12-06 09:59 UTC, amassarwi commented on app/config.js
> +
extra empty line

2020-12-06 09:59 UTC, amassarwi commented on app/components/views/GetStartedPage/hooks.js
> +
extra empty line

2020-12-08 17:04 UTC, guilhermemntt commented
Empty lines have been removed and PR rebased.

2020-12-10 19:55 UTC, guilhermemntt commented
As discussed on Matrix, some changes have been undone due to a decision reconsideration. In this way, ``allowed_external_requests`` will be kept in the global config.

2020-12-18 11:07 UTC, jholdstock requested changes

2020-12-18 11:07 UTC, jholdstock commented on app/config.js
> +    cfgConstants.ALLOW_EXTERNAL_REQUESTS
I think this line needs to be removed

2020-12-18 11:07 UTC, jholdstock commented on app/constants/config.js
> +export const ALLOW_EXTERNAL_REQUESTS = "allowed_external_requests";
`ALLOWED_EXTERNAL_REQUESTS` is a more descriptive name for this than `ALLOW_EXTERNAL_REQUESTS`

2020-12-21 18:26 UTC, guilhermemntt commented
Thanks for the relevant comments @jholdstock.

2020-12-22 09:06 UTC, jholdstock approved these changes

2021-01-04 20:25 UTC, vctt94 approved these changes
Thanks for this PR.

Tested some basic functionalities and all went fine. LGTM

2021-01-05 17:42 UTC, merged