Add v1.6.0 release notes
decred/decrediton pull request #3048
Opened 2020-12-07 17:08 UTC by alexlyp

2020-12-07 19:12 UTC, matheusd reviewed
Typography for the release notes page seems pretty broken.

A quick & dirty fix to improve it a bit would be adding the following in `GetStarted.module.css`:

```css
.releaseNotesText p,
.releaseNotesText ul,
.releaseNotesText ol,
.releaseNotesText h1,
.releaseNotesText h2,
.releaseNotesText h3,
.releaseNotesText h4 {
  margin-bottom: 1em;
}
```

Also, there are some .yarncache files in the commit.

2020-12-08 10:40 UTC, jholdstock requested changes
- Maybe unrelated to the changes in this PR - a "Newer Version" link is displayed at the top of the 1.6.0 release note, even though it is the newest.

- Some image options. I believe @behindtext and @linnutee agreed to go with the third option, and tbh I think I prefer that one too. Beware that these are ~8MB each, so probably need some compression.

![1 6_mix4_30](https://user-images.githubusercontent.com/6762864/101473071-4ba9aa80-3941-11eb-9b39-8e77dc64ed07.gif)
![1 6_mix555_30](https://user-images.githubusercontent.com/6762864/101473076-4c424100-3941-11eb-80fd-7e163a42db9d.gif)
![1 6_mix4_distort2_30](https://user-images.githubusercontent.com/6762864/101473087-4f3d3180-3941-11eb-8370-9249a91a6a5c.gif)

2020-12-08 10:40 UTC, jholdstock commented on app/i18n/docs/en/ReleaseNotes/v1.6.0.md
> +  intervention with private passprhase entry to create needed mixed and unmixed
```suggestion
  intervention with private passphrase entry to create needed mixed and unmixed 
```

2020-12-08 10:40 UTC, jholdstock commented on app/i18n/docs/en/ReleaseNotes/v1.6.0.md
> +  account.  And we have restricted address generation to the mixed account,
```suggestion
  account.  Additionally, we have restricted address generation to the mixed account,
```

2020-12-08 10:40 UTC, jholdstock commented on app/components/views/GetStartedPage/GetStarted.module.css
> +
To indent lists and ensure the bullets are displayed
```suggestion

.releaseNotesText ul,
.releaseNotesText ol {
  padding-left: 2em;
}
```

2020-12-08 10:40 UTC, jholdstock commented on app/i18n/docs/en/ReleaseNotes/v1.6.0.md
> +users have to add VSPs via apikey.
```suggestion
users have to add VSPs via API key.  
```

2020-12-08 10:40 UTC, jholdstock commented on app/i18n/docs/en/ReleaseNotes/v1.6.0.md
> +  always) sufficient.  If successful the mixed split ticket funding transaction,
Suggest some extra commas and a couple less words in this list:

>  If successful, the mixed split ticket funding transaction, the ticket, and the ticket's fee, should all be seen on the overview.

2020-12-08 10:40 UTC, jholdstock commented on app/i18n/docs/en/ReleaseNotes/v1.6.0.md
> +  * Peer count is now shown on the side bar.  This should allviate issues where
```suggestion
  * Peer count is now shown on the side bar.  This should alleviate issues where
```

2020-12-08 15:22 UTC, jholdstock commented on app/components/views/GetStartedPage/GetStarted.module.css
> +
Just noticed this is likely fixed by #3033 3051

2020-12-08 17:15 UTC, matheusd approved these changes

2020-12-08 19:40 UTC, merged

2020-12-09 15:05 UTC, jholdstock commented on app/components/views/GetStartedPage/GetStarted.module.css
> +
@ay-p I think this needs to be double-checked. It was committed into this PR, but this PR is not rebased onto #3051

The result could be a double-indentation on the lists.