Remove util type checks
decred/decrediton pull request #3135
Opened 2021-01-09 20:28 UTC by guilhermemntt

Closes https://github.com/decred/decrediton/issues/3131.

2021-01-09 20:37 UTC, amassarwi requested changes
Thanks for this PR, left an inline suggestion.

2021-01-09 20:37 UTC, amassarwi commented on app/actions/StatisticsActions.js
> +      series[s.name] !== undefined ? s.valueFormatFunc(series[s.name]) : null
This isn't enough, you could also check if typeof x === "undefined" but I would rather user lodash `isUndefined` func for that.

Lodash may have it's own version of `isNumber, isNullOrUndefined` funcs as well, checkout their documentation.

2021-01-10 19:12 UTC, guilhermemntt commented
Thanks @amassarwi, you're totally right. Just to be clearer: ``something === "undefined"`` throws error if ``something`` hasn't been defined yet. So, there was a trap in ``@deprecated`` annotation and its suggestion. Following your suggestion now, ``lodash`` has all these type check, including [isNil](https://lodash.com/docs/4.17.15) which is equivalent to ``isNullOrUndefined``.

2021-01-10 19:13 UTC, amassarwi approved these changes
Noice 👍

2021-01-19 12:24 UTC, vctt94 commented
needs rebase

2021-01-19 14:34 UTC, guilhermemntt commented
Rebased.

2021-04-20 18:50 UTC, alexlyp commented
Quite a few conflicts that will need to be dealt with.

2021-05-03 19:59 UTC, matheusd approved these changes
Nice job. Thanks for this!

2021-05-03 20:12 UTC, merged