LN Pages refactoring
decred/decrediton pull request #3325
Opened 2021-03-21 08:26 UTC by guilhermemntt

WIP. Almost there.

2021-03-22 11:04 UTC, amassarwi requested changes
@guilhermemntt Good job on this one mate, code looks neat, left few suggestions.

2021-03-22 11:04 UTC, amassarwi commented on app/components/views/LNPage/PaymentsTab/PaymentsTab.jsx
> +          <div className={styles.decodingError}>{"" + decodingError}</div>
```suggestion
          <div className={styles.decodingError}>{decodingError || ""}</div>
```

2021-03-22 11:04 UTC, amassarwi commented on app/components/views/LNPage/PaymentsTab/hooks.js
> +    setPayRequest(("" + e.target.value).trim());
```suggestion
    setPayRequest((e.target.value || "").trim());
```

2021-03-22 11:04 UTC, amassarwi commented on app/components/views/LNPage/WalletTab/WalletTab.module.css
> +/* BalanceHeader */
I would suggest creating `BalanceHeader.module.css` where there classes are used

2021-03-22 11:04 UTC, amassarwi commented on app/containers/Wallet.jsx
> +import LNPage from "components/views/LNPage/LNPage";
create `index.js` file to avoid this extra verbose.

2021-03-22 11:08 UTC, amassarwi commented
Probably the LN guys want to try this out - @matheusd  @fguisso @vctt94  

I'll be setting testnet LN wallet now to give it a try as well.

2021-03-22 13:23 UTC, matheusd reviewed
Functionally, seems to be working fine

2021-03-22 17:12 UTC, amassarwi commented
Please add Closes https://github.com/decred/decrediton/issues/3260 & Closes https://github.com/decred/decrediton/issues/3259 to the PR's description, as this commit refactors the last piece to functional approach with css modules.

I will follow up with 1-2 cleanup PRs tonight which will finally close #2438 & #2439. Historic moment 🎉.

2021-03-22 21:54 UTC, guilhermemntt commented
Rebased @amassarwi !

2021-03-23 15:47 UTC, alexlyp approved these changes

2021-03-23 15:47 UTC, merged