[electron] Remove winston as a dependency
decred/decrediton pull request #3536
Opened 2021-07-20 19:18 UTC by matheusd

This removes the winston log library as a dependency from the project. This helps reduce the number of dependencies on the main electron layer.

This is done by implementing a very basic logger that replicates the features we were using from winston: writing both to a log file and to the terminal when `debug` is set.

Dependencies of the main electron layer before winston is removed:

![electron-deps-winston](https://user-images.githubusercontent.com/1752493/126382618-153804ff-54e9-43d9-9d41-f10fdd96dabe.png)

After removing winston:
![electron-deps-no-winston](https://user-images.githubusercontent.com/1752493/126382606-d72fcfc3-0b2b-4410-8d9c-2438f7a96923.png)

2021-07-21 12:05 UTC, amassarwi commented on app/main.development.js
> +  logger.log("error", "UNCAUGHT EXCEPTION: " + err);
string template

2021-07-21 12:15 UTC, amassarwi approved these changes
Nice work 🥇 
Left some minors

2021-07-21 12:15 UTC, amassarwi commented on app/main_dev/launch.js
> +          logger.log("error", "tx stream error: " + e)
string template

2021-07-21 12:15 UTC, amassarwi commented on app/main_dev/launch.js
> +      logger.log("error", "dcrd closed due to an error: " + lastDcrdErr);
string template

2021-07-21 12:15 UTC, amassarwi commented on app/wallet/app.js
> +  const logMsg = msg + " " + logArgs.join(" ");
string template

2021-07-21 19:55 UTC, bgptr requested changes
The code looks good and works fine.
I found only one critical issue: when I try to navigate to `Logs` view the application quits with this error message:

``` 2021-07-21 21:44:22.502 [ERR] DCTN: UNCAUGHT EXCEPTION: TypeError: Cannot read property 'find' of undefined
/home/bgptr/go/src/github.com/decred/decrediton/app/main.js:729
_fs.default.existsSync(walletsDirectory)||_fs.default.mkdirSync(walletsDirectory,{recursive:true});_fs.default.existsSync(mainnetWalletsPath)||_fs.default.mkdirSync(mainnetWalletsPath,{recursive:true});_fs.default.existsSync(testnetWalletsPath)||_fs.default.mkdirSync(testnetWalletsPath,{recursive:true});(0,_paths.checkAndInitWalletCfg)(true);(0,_paths.checkAndInitWalletCfg)(false);logger.log("info","Using config/data from:"+_electron.app.getPath("userData"));logger.log("info",`Versions: Decrediton: ${_electron.app.getVersion()}, `+`Electron: ${process.versions.electron}, `+`Chrome: ${process.versions.chrome}`);process.on("uncaughtException",err=>{logger.log("error",`UNCAUGHT EXCEPTION: ${err}`);throw err;});const installExtensions=async()=>{if(true){const extensions=[_electronDevtoolsInstaller.REACT_DEVELOPER_TOOLS,_electronDevtoolsInstaller.REDUX_DEVTOOLS];const forceDownload=!!process.env.UPGRADE_EXTENSIONS;for(const name of extensions){try{await(0,_electronDevtoolsInstaller.default)(name,forceDownload);}catch(e){console.log("Error installing extension: "+e);}}}};const{ipcMain}=__webpack_require__(/*! electron */"electron");// handleEvent listens on the given channel for ipcRenderer.invoke() calls and


                                                                  ^

TypeError: Cannot read property 'find' of undefined
    at IpcMainImpl.<anonymous> (/home/bgptr/go/src/github.com/decred/decrediton/app/main.js:8821:42)
    at IpcMainImpl.emit (events.js:315:20)
    at Object.<anonymous> (electron/js2c/browser_init.js:161:10351)
    at Object.emit (events.js:315:20)
```

2021-07-22 13:09 UTC, matheusd commented
Nice catch! Updated.

2021-07-22 13:16 UTC, bgptr approved these changes

2021-07-29 18:53 UTC, alexlyp approved these changes

2021-07-29 18:53 UTC, merged