Improve VSPSelect usability and responsivity
decred/decrediton pull request #3563
Opened 2021-09-30 02:31 UTC by guilhermemntt

This PR improves the responsivity of the ``VSPSelect`` and ``AutoBuyerSettingsModal`` components by:

- Stretching the account select to adjust the modal width.
- Enabling clicks on the right corner of a VSP option (currently, there's a padding inserted by ``react-select``).
- Inserting ellipsis on long VSP host names.

Also, the small "close" icon should clear the current input only when typing, since it's useless for clearing the selected VSP.

2021-09-30 08:55 UTC, bgptr requested changes
Looks nice. I found only one thing: the tooltips disappeared. 

This is how it looks like on master now:
<img width="271" alt="2021-09-30_10-50" src="https://user-images.githubusercontent.com/52497040/135420757-06a8ed56-249f-4dda-aea5-5789773cdf45.png">

2021-09-30 15:25 UTC, guilhermemntt commented
Hey @bgptr, thanks for the review. That last commit solves the issue by detaching the ``text-overflow`` from the relative component.

2021-09-30 18:09 UTC, bgptr approved these changes
Hey @guilhermemntt Perfect, the tooltips are back. Thanks!

2021-10-01 17:46 UTC, alexlyp approved these changes

2021-10-01 17:46 UTC, merged