Fix header spacing on Governance tab
decred/decrediton pull request #3626
Opened 2021-12-30 13:46 UTC by jholdstock

Ensure the spacing between Title and Description is 5px, as specified in #3404. More detail in commit messages.

2021-12-30 17:52 UTC, bgptr requested changes
@jholdstock, thanks for this PR. Looks nice, only the description part looks a bit more crowded now. There should be `10px` margin between the description lines in the latest design: https://www.figma.com/file/EanUbqJmPs8EMqY26j9zwo/decred---piui---decrediton?node-id=92%3A2457

design vs current state:
![image](https://user-images.githubusercontent.com/52497040/147776086-73fd6fd9-e35d-4ced-8988-daf6e6956fe4.png)

2022-01-02 10:31 UTC, jholdstock commented
Right, I see the problem here. I was only seeing one line of description because I had the external HTTP request for treasury balance disabled. Fixing

2022-01-02 11:24 UTC, jholdstock commented
Pushed some changes,  I think this now also fixes #3627

2022-01-02 11:25 UTC, jholdstock commented on app/components/layout/TabbedPage/TabbedPage.module.css
> +  top: 55px;
:nauseated_face:

2022-01-02 19:05 UTC, bgptr approved these changes
Tested, and looks nice.

2022-01-03 15:16 UTC, alexlyp approved these changes

2022-01-03 15:17 UTC, merged